# Usar Node.js como base
FROM node:18

# Definir o diretório de trabalho
WORKDIR /app

# Copiar arquivos essenciais
COPY package.json package-lock.json ./

# Instalar dependências
RUN npm install

# Copiar o código-fonte
COPY . .

# Criar o build do frontend
RUN npm run build

# Expor a porta 3000
EXPOSE 3000

# Iniciar o servidor do React
CMD ["npm", "start"]
